### PR TITLE
Inject a "send()" function into rivescript javascript scripts. (+ some refactoring)

### PR DESCRIPTION
**Pull request by Okazari**

### CODE REVIEW

**Comment by Okazari** [comment]
I just wasn't able to try the irc part. @TheFreakLord Could you try ?

**Comment by Okazari** [comment]
See https://github.com/Okazari/mystery-bot/tree/botpress for the example

**Comment by slvnperron** [comment]
Has this been tested ?

**Comment by Okazari** [comment]
I tested it on messenger/discord and @TheFreakLord tested the irc part

**Comment by slvnperron** [comment]
great! thanks for the contribution :) 
would be nice to eventually refactor it to inject new deliveries at run-time

**Pull request merged**
